// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ballast.proto

// Package ballast.v1 is the agent <-> centre gRPC contract for Ballast.
//
// The Go desired-state schema in api/types is the source of truth. These
// messages mirror it for transport only; the single mapping between the two
// lives in api/proto/convert.go so the wire form can never silently diverge
// from the schema. Extend this file in lockstep with api/types, never alone.

package ballastpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterHost_FullMethodName     = "/ballast.v1.AgentService/RegisterHost"
	AgentService_PullDesiredState_FullMethodName = "/ballast.v1.AgentService/PullDesiredState"
	AgentService_ReportStatus_FullMethodName     = "/ballast.v1.AgentService/ReportStatus"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is served by the centre and consumed by each host agent. It is
// deliberately small: announce, pull desired state, report status. The centre
// never imperatively drives a host through this service; it only serves desired
// state and accepts reported status.
type AgentServiceClient interface {
	// RegisterHost announces an agent to the centre on startup and reports
	// initial inventory. The centre returns the host identity (UID) the agent
	// should use for subsequent calls. Calling it again with the same host name
	// is idempotent and returns the existing identity.
	RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error)
	// PullDesiredState returns the current desired Host for the calling agent,
	// plus any cluster assignment. The agent caches the result as its
	// last-honoured state and keeps enforcing it if the centre later becomes
	// unreachable.
	PullDesiredState(ctx context.Context, in *PullDesiredStateRequest, opts ...grpc.CallOption) (*PullDesiredStateResponse, error)
	// ReportStatus delivers an agent's observed status to the centre, carrying
	// ObservedGeneration and the Autonomous flag so the centre can tell whether
	// an object is settled and whether the agent is running on cached state.
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHostResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PullDesiredState(ctx context.Context, in *PullDesiredStateRequest, opts ...grpc.CallOption) (*PullDesiredStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullDesiredStateResponse)
	err := c.cc.Invoke(ctx, AgentService_PullDesiredState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is served by the centre and consumed by each host agent. It is
// deliberately small: announce, pull desired state, report status. The centre
// never imperatively drives a host through this service; it only serves desired
// state and accepts reported status.
type AgentServiceServer interface {
	// RegisterHost announces an agent to the centre on startup and reports
	// initial inventory. The centre returns the host identity (UID) the agent
	// should use for subsequent calls. Calling it again with the same host name
	// is idempotent and returns the existing identity.
	RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error)
	// PullDesiredState returns the current desired Host for the calling agent,
	// plus any cluster assignment. The agent caches the result as its
	// last-honoured state and keeps enforcing it if the centre later becomes
	// unreachable.
	PullDesiredState(context.Context, *PullDesiredStateRequest) (*PullDesiredStateResponse, error)
	// ReportStatus delivers an agent's observed status to the centre, carrying
	// ObservedGeneration and the Autonomous flag so the centre can tell whether
	// an object is settled and whether the agent is running on cached state.
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedAgentServiceServer) PullDesiredState(context.Context, *PullDesiredStateRequest) (*PullDesiredStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullDesiredState not implemented")
}
func (UnimplementedAgentServiceServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterHost(ctx, req.(*RegisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PullDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PullDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PullDesiredState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PullDesiredState(ctx, req.(*PullDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ballast.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _AgentService_RegisterHost_Handler,
		},
		{
			MethodName: "PullDesiredState",
			Handler:    _AgentService_PullDesiredState_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _AgentService_ReportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ballast.proto",
}
