// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ballast.proto

// Package ballast.v1 is the agent <-> centre gRPC contract for Ballast.
//
// The Go desired-state schema in api/types is the source of truth. These
// messages mirror it for transport only; the single mapping between the two
// lives in api/proto/convert.go so the wire form can never silently diverge
// from the schema. Extend this file in lockstep with api/types, never alone.

package ballastpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_PENDING     Phase = 1
	Phase_PHASE_PROGRESSING Phase = 2
	Phase_PHASE_READY       Phase = 3
	Phase_PHASE_DEGRADED    Phase = 4
	Phase_PHASE_ERROR       Phase = 5
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PENDING",
		2: "PHASE_PROGRESSING",
		3: "PHASE_READY",
		4: "PHASE_DEGRADED",
		5: "PHASE_ERROR",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_PENDING":     1,
		"PHASE_PROGRESSING": 2,
		"PHASE_READY":       3,
		"PHASE_DEGRADED":    4,
		"PHASE_ERROR":       5,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_ballast_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_ballast_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{0}
}

type RebootPolicy int32

const (
	RebootPolicy_REBOOT_POLICY_UNSPECIFIED RebootPolicy = 0
	RebootPolicy_REBOOT_POLICY_NEVER       RebootPolicy = 1
	RebootPolicy_REBOOT_POLICY_IF_NEEDED   RebootPolicy = 2
)

// Enum value maps for RebootPolicy.
var (
	RebootPolicy_name = map[int32]string{
		0: "REBOOT_POLICY_UNSPECIFIED",
		1: "REBOOT_POLICY_NEVER",
		2: "REBOOT_POLICY_IF_NEEDED",
	}
	RebootPolicy_value = map[string]int32{
		"REBOOT_POLICY_UNSPECIFIED": 0,
		"REBOOT_POLICY_NEVER":       1,
		"REBOOT_POLICY_IF_NEEDED":   2,
	}
)

func (x RebootPolicy) Enum() *RebootPolicy {
	p := new(RebootPolicy)
	*p = x
	return p
}

func (x RebootPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RebootPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_ballast_proto_enumTypes[1].Descriptor()
}

func (RebootPolicy) Type() protoreflect.EnumType {
	return &file_ballast_proto_enumTypes[1]
}

func (x RebootPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RebootPolicy.Descriptor instead.
func (RebootPolicy) EnumDescriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{1}
}

type SETTeamingMode int32

const (
	SETTeamingMode_SET_TEAMING_MODE_UNSPECIFIED        SETTeamingMode = 0
	SETTeamingMode_SET_TEAMING_MODE_SWITCH_INDEPENDENT SETTeamingMode = 1
)

// Enum value maps for SETTeamingMode.
var (
	SETTeamingMode_name = map[int32]string{
		0: "SET_TEAMING_MODE_UNSPECIFIED",
		1: "SET_TEAMING_MODE_SWITCH_INDEPENDENT",
	}
	SETTeamingMode_value = map[string]int32{
		"SET_TEAMING_MODE_UNSPECIFIED":        0,
		"SET_TEAMING_MODE_SWITCH_INDEPENDENT": 1,
	}
)

func (x SETTeamingMode) Enum() *SETTeamingMode {
	p := new(SETTeamingMode)
	*p = x
	return p
}

func (x SETTeamingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SETTeamingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ballast_proto_enumTypes[2].Descriptor()
}

func (SETTeamingMode) Type() protoreflect.EnumType {
	return &file_ballast_proto_enumTypes[2]
}

func (x SETTeamingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SETTeamingMode.Descriptor instead.
func (SETTeamingMode) EnumDescriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{2}
}

type SETLoadBalancing int32

const (
	SETLoadBalancing_SET_LOAD_BALANCING_UNSPECIFIED SETLoadBalancing = 0
	SETLoadBalancing_SET_LOAD_BALANCING_HYPERV_PORT SETLoadBalancing = 1
	SETLoadBalancing_SET_LOAD_BALANCING_DYNAMIC     SETLoadBalancing = 2
)

// Enum value maps for SETLoadBalancing.
var (
	SETLoadBalancing_name = map[int32]string{
		0: "SET_LOAD_BALANCING_UNSPECIFIED",
		1: "SET_LOAD_BALANCING_HYPERV_PORT",
		2: "SET_LOAD_BALANCING_DYNAMIC",
	}
	SETLoadBalancing_value = map[string]int32{
		"SET_LOAD_BALANCING_UNSPECIFIED": 0,
		"SET_LOAD_BALANCING_HYPERV_PORT": 1,
		"SET_LOAD_BALANCING_DYNAMIC":     2,
	}
)

func (x SETLoadBalancing) Enum() *SETLoadBalancing {
	p := new(SETLoadBalancing)
	*p = x
	return p
}

func (x SETLoadBalancing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SETLoadBalancing) Descriptor() protoreflect.EnumDescriptor {
	return file_ballast_proto_enumTypes[3].Descriptor()
}

func (SETLoadBalancing) Type() protoreflect.EnumType {
	return &file_ballast_proto_enumTypes[3]
}

func (x SETLoadBalancing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SETLoadBalancing.Descriptor instead.
func (SETLoadBalancing) EnumDescriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{3}
}

type WitnessType int32

const (
	WitnessType_WITNESS_TYPE_UNSPECIFIED WitnessType = 0
	WitnessType_WITNESS_TYPE_NONE        WitnessType = 1
	WitnessType_WITNESS_TYPE_FILE_SHARE  WitnessType = 2
	WitnessType_WITNESS_TYPE_CLOUD       WitnessType = 3
	WitnessType_WITNESS_TYPE_DISK        WitnessType = 4
)

// Enum value maps for WitnessType.
var (
	WitnessType_name = map[int32]string{
		0: "WITNESS_TYPE_UNSPECIFIED",
		1: "WITNESS_TYPE_NONE",
		2: "WITNESS_TYPE_FILE_SHARE",
		3: "WITNESS_TYPE_CLOUD",
		4: "WITNESS_TYPE_DISK",
	}
	WitnessType_value = map[string]int32{
		"WITNESS_TYPE_UNSPECIFIED": 0,
		"WITNESS_TYPE_NONE":        1,
		"WITNESS_TYPE_FILE_SHARE":  2,
		"WITNESS_TYPE_CLOUD":       3,
		"WITNESS_TYPE_DISK":        4,
	}
)

func (x WitnessType) Enum() *WitnessType {
	p := new(WitnessType)
	*p = x
	return p
}

func (x WitnessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WitnessType) Descriptor() protoreflect.EnumDescriptor {
	return file_ballast_proto_enumTypes[4].Descriptor()
}

func (WitnessType) Type() protoreflect.EnumType {
	return &file_ballast_proto_enumTypes[4]
}

func (x WitnessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WitnessType.Descriptor instead.
func (WitnessType) EnumDescriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{4}
}

type RegisterHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_name is the stable, human-meaningful host identifier (ObjectMeta.Name).
	HostName string `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// fqdn the agent believes it is reachable as.
	Fqdn string `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// inventory observed at registration time (physical adapters at minimum).
	Inventory *HostInventory `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	// agent_version for diagnostics and compatibility checks.
	AgentVersion  string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_ballast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterHostRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RegisterHostRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *RegisterHostRequest) GetInventory() *HostInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *RegisterHostRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterHostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uid is the immutable identity the centre assigns (or has) for this host.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// known is true when the centre already had desired state for this host.
	Known         bool `protobuf:"varint,2,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_ballast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHostResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RegisterHostResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

type PullDesiredStateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	HostName string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Uid      string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// known_generation lets the centre answer cheaply when nothing changed; the
	// agent sends the Generation it currently holds, 0 if it holds none.
	KnownGeneration int64 `protobuf:"varint,3,opt,name=known_generation,json=knownGeneration,proto3" json:"known_generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullDesiredStateRequest) Reset() {
	*x = PullDesiredStateRequest{}
	mi := &file_ballast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullDesiredStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullDesiredStateRequest) ProtoMessage() {}

func (x *PullDesiredStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullDesiredStateRequest.ProtoReflect.Descriptor instead.
func (*PullDesiredStateRequest) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{2}
}

func (x *PullDesiredStateRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *PullDesiredStateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PullDesiredStateRequest) GetKnownGeneration() int64 {
	if x != nil {
		return x.KnownGeneration
	}
	return 0
}

type PullDesiredStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// has_desired_state is false when the centre has no Host assigned yet.
	HasDesiredState bool `protobuf:"varint,1,opt,name=has_desired_state,json=hasDesiredState,proto3" json:"has_desired_state,omitempty"`
	// unchanged is true when known_generation already matches the centre's
	// Generation, in which case host may be omitted.
	Unchanged bool  `protobuf:"varint,2,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	Host      *Host `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// cluster_assignment tells the host whether it belongs to a cluster and
	// whether it is the designated former. Absent when the host is standalone.
	ClusterAssignment *ClusterAssignment `protobuf:"bytes,4,opt,name=cluster_assignment,json=clusterAssignment,proto3" json:"cluster_assignment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullDesiredStateResponse) Reset() {
	*x = PullDesiredStateResponse{}
	mi := &file_ballast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullDesiredStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullDesiredStateResponse) ProtoMessage() {}

func (x *PullDesiredStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullDesiredStateResponse.ProtoReflect.Descriptor instead.
func (*PullDesiredStateResponse) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{3}
}

func (x *PullDesiredStateResponse) GetHasDesiredState() bool {
	if x != nil {
		return x.HasDesiredState
	}
	return false
}

func (x *PullDesiredStateResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

func (x *PullDesiredStateResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *PullDesiredStateResponse) GetClusterAssignment() *ClusterAssignment {
	if x != nil {
		return x.ClusterAssignment
	}
	return nil
}

type ReportStatusRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	HostName string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Uid      string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status   *HostStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// cluster_name and cluster_status are set when the host is a cluster member
	// and has observed cluster state to report (typically from the former).
	ClusterName   string         `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterStatus *ClusterStatus `protobuf:"bytes,5,opt,name=cluster_status,json=clusterStatus,proto3" json:"cluster_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_ballast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{4}
}

func (x *ReportStatusRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ReportStatusRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReportStatusRequest) GetStatus() *HostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ReportStatusRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ReportStatusRequest) GetClusterStatus() *ClusterStatus {
	if x != nil {
		return x.ClusterStatus
	}
	return nil
}

type ReportStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is false if the centre rejected the report (e.g. unknown host).
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_ballast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{5}
}

func (x *ReportStatusResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_ballast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ObjectMeta) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Condition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_ballast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{7}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Condition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec          *HostSpec              `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *HostStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_ballast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{8}
}

func (x *Host) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Host) GetSpec() *HostSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Host) GetStatus() *HostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HostSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Fqdn             string                 `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	EnableHypervRole bool                   `protobuf:"varint,2,opt,name=enable_hyperv_role,json=enableHypervRole,proto3" json:"enable_hyperv_role,omitempty"`
	Networking       *HostNetworkingSpec    `protobuf:"bytes,3,opt,name=networking,proto3" json:"networking,omitempty"`
	Storage          *HostStorageSpec       `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	// cluster_membership is optional; absence means standalone.
	ClusterMembership *ClusterMembershipSpec `protobuf:"bytes,5,opt,name=cluster_membership,json=clusterMembership,proto3" json:"cluster_membership,omitempty"`
	RebootPolicy      RebootPolicy           `protobuf:"varint,6,opt,name=reboot_policy,json=rebootPolicy,proto3,enum=ballast.v1.RebootPolicy" json:"reboot_policy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostSpec) Reset() {
	*x = HostSpec{}
	mi := &file_ballast_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSpec) ProtoMessage() {}

func (x *HostSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSpec.ProtoReflect.Descriptor instead.
func (*HostSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{9}
}

func (x *HostSpec) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *HostSpec) GetEnableHypervRole() bool {
	if x != nil {
		return x.EnableHypervRole
	}
	return false
}

func (x *HostSpec) GetNetworking() *HostNetworkingSpec {
	if x != nil {
		return x.Networking
	}
	return nil
}

func (x *HostSpec) GetStorage() *HostStorageSpec {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *HostSpec) GetClusterMembership() *ClusterMembershipSpec {
	if x != nil {
		return x.ClusterMembership
	}
	return nil
}

func (x *HostSpec) GetRebootPolicy() RebootPolicy {
	if x != nil {
		return x.RebootPolicy
	}
	return RebootPolicy_REBOOT_POLICY_UNSPECIFIED
}

type HostStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Phase              Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=ballast.v1.Phase" json:"phase,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,2,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	HypervInstalled    bool                   `protobuf:"varint,3,opt,name=hyperv_installed,json=hypervInstalled,proto3" json:"hyperv_installed,omitempty"`
	RebootRequired     bool                   `protobuf:"varint,4,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	Autonomous         bool                   `protobuf:"varint,5,opt,name=autonomous,proto3" json:"autonomous,omitempty"`
	LastContact        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_contact,json=lastContact,proto3" json:"last_contact,omitempty"`
	Inventory          *HostInventory         `protobuf:"bytes,7,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Conditions         []*Condition           `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HostStatus) Reset() {
	*x = HostStatus{}
	mi := &file_ballast_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatus) ProtoMessage() {}

func (x *HostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatus.ProtoReflect.Descriptor instead.
func (*HostStatus) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{10}
}

func (x *HostStatus) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *HostStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *HostStatus) GetHypervInstalled() bool {
	if x != nil {
		return x.HypervInstalled
	}
	return false
}

func (x *HostStatus) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *HostStatus) GetAutonomous() bool {
	if x != nil {
		return x.Autonomous
	}
	return false
}

func (x *HostStatus) GetLastContact() *timestamppb.Timestamp {
	if x != nil {
		return x.LastContact
	}
	return nil
}

func (x *HostStatus) GetInventory() *HostInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *HostStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type HostInventory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PhysicalAdapters []*PhysicalAdapter     `protobuf:"bytes,1,rep,name=physical_adapters,json=physicalAdapters,proto3" json:"physical_adapters,omitempty"`
	PhysicalDisks    []*PhysicalDisk        `protobuf:"bytes,2,rep,name=physical_disks,json=physicalDisks,proto3" json:"physical_disks,omitempty"`
	TotalMemoryBytes uint64                 `protobuf:"varint,3,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	LogicalCpus      int32                  `protobuf:"varint,4,opt,name=logical_cpus,json=logicalCpus,proto3" json:"logical_cpus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostInventory) Reset() {
	*x = HostInventory{}
	mi := &file_ballast_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInventory) ProtoMessage() {}

func (x *HostInventory) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInventory.ProtoReflect.Descriptor instead.
func (*HostInventory) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{11}
}

func (x *HostInventory) GetPhysicalAdapters() []*PhysicalAdapter {
	if x != nil {
		return x.PhysicalAdapters
	}
	return nil
}

func (x *HostInventory) GetPhysicalDisks() []*PhysicalDisk {
	if x != nil {
		return x.PhysicalDisks
	}
	return nil
}

func (x *HostInventory) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *HostInventory) GetLogicalCpus() int32 {
	if x != nil {
		return x.LogicalCpus
	}
	return 0
}

type PhysicalAdapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	LinkSpeedBps  uint64                 `protobuf:"varint,3,opt,name=link_speed_bps,json=linkSpeedBps,proto3" json:"link_speed_bps,omitempty"`
	Up            bool                   `protobuf:"varint,4,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalAdapter) Reset() {
	*x = PhysicalAdapter{}
	mi := &file_ballast_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalAdapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalAdapter) ProtoMessage() {}

func (x *PhysicalAdapter) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalAdapter.ProtoReflect.Descriptor instead.
func (*PhysicalAdapter) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{12}
}

func (x *PhysicalAdapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalAdapter) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PhysicalAdapter) GetLinkSpeedBps() uint64 {
	if x != nil {
		return x.LinkSpeedBps
	}
	return 0
}

func (x *PhysicalAdapter) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type PhysicalDisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	CanPool       bool                   `protobuf:"varint,4,opt,name=can_pool,json=canPool,proto3" json:"can_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalDisk) Reset() {
	*x = PhysicalDisk{}
	mi := &file_ballast_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalDisk) ProtoMessage() {}

func (x *PhysicalDisk) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalDisk.ProtoReflect.Descriptor instead.
func (*PhysicalDisk) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{13}
}

func (x *PhysicalDisk) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PhysicalDisk) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PhysicalDisk) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PhysicalDisk) GetCanPool() bool {
	if x != nil {
		return x.CanPool
	}
	return false
}

type HostNetworkingSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Switches        []*VirtualSwitchSpec   `protobuf:"bytes,1,rep,name=switches,proto3" json:"switches,omitempty"`
	ManagementVnics []*ManagementVNICSpec  `protobuf:"bytes,2,rep,name=management_vnics,json=managementVnics,proto3" json:"management_vnics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HostNetworkingSpec) Reset() {
	*x = HostNetworkingSpec{}
	mi := &file_ballast_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostNetworkingSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostNetworkingSpec) ProtoMessage() {}

func (x *HostNetworkingSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostNetworkingSpec.ProtoReflect.Descriptor instead.
func (*HostNetworkingSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{14}
}

func (x *HostNetworkingSpec) GetSwitches() []*VirtualSwitchSpec {
	if x != nil {
		return x.Switches
	}
	return nil
}

func (x *HostNetworkingSpec) GetManagementVnics() []*ManagementVNICSpec {
	if x != nil {
		return x.ManagementVnics
	}
	return nil
}

type VirtualSwitchSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamMembers       []string               `protobuf:"bytes,2,rep,name=team_members,json=teamMembers,proto3" json:"team_members,omitempty"`
	TeamingMode       SETTeamingMode         `protobuf:"varint,3,opt,name=teaming_mode,json=teamingMode,proto3,enum=ballast.v1.SETTeamingMode" json:"teaming_mode,omitempty"`
	LoadBalancing     SETLoadBalancing       `protobuf:"varint,4,opt,name=load_balancing,json=loadBalancing,proto3,enum=ballast.v1.SETLoadBalancing" json:"load_balancing,omitempty"`
	AllowManagementOs bool                   `protobuf:"varint,5,opt,name=allow_management_os,json=allowManagementOs,proto3" json:"allow_management_os,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VirtualSwitchSpec) Reset() {
	*x = VirtualSwitchSpec{}
	mi := &file_ballast_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualSwitchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualSwitchSpec) ProtoMessage() {}

func (x *VirtualSwitchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualSwitchSpec.ProtoReflect.Descriptor instead.
func (*VirtualSwitchSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{15}
}

func (x *VirtualSwitchSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualSwitchSpec) GetTeamMembers() []string {
	if x != nil {
		return x.TeamMembers
	}
	return nil
}

func (x *VirtualSwitchSpec) GetTeamingMode() SETTeamingMode {
	if x != nil {
		return x.TeamingMode
	}
	return SETTeamingMode_SET_TEAMING_MODE_UNSPECIFIED
}

func (x *VirtualSwitchSpec) GetLoadBalancing() SETLoadBalancing {
	if x != nil {
		return x.LoadBalancing
	}
	return SETLoadBalancing_SET_LOAD_BALANCING_UNSPECIFIED
}

func (x *VirtualSwitchSpec) GetAllowManagementOs() bool {
	if x != nil {
		return x.AllowManagementOs
	}
	return false
}

type ManagementVNICSpec struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SwitchName string                 `protobuf:"bytes,2,opt,name=switch_name,json=switchName,proto3" json:"switch_name,omitempty"`
	VlanId     int32                  `protobuf:"varint,3,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// ip_config absent means DHCP.
	IpConfig           *IPConfig `protobuf:"bytes,4,opt,name=ip_config,json=ipConfig,proto3" json:"ip_config,omitempty"`
	MinBandwidthWeight int32     `protobuf:"varint,5,opt,name=min_bandwidth_weight,json=minBandwidthWeight,proto3" json:"min_bandwidth_weight,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ManagementVNICSpec) Reset() {
	*x = ManagementVNICSpec{}
	mi := &file_ballast_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementVNICSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementVNICSpec) ProtoMessage() {}

func (x *ManagementVNICSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementVNICSpec.ProtoReflect.Descriptor instead.
func (*ManagementVNICSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{16}
}

func (x *ManagementVNICSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagementVNICSpec) GetSwitchName() string {
	if x != nil {
		return x.SwitchName
	}
	return ""
}

func (x *ManagementVNICSpec) GetVlanId() int32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *ManagementVNICSpec) GetIpConfig() *IPConfig {
	if x != nil {
		return x.IpConfig
	}
	return nil
}

func (x *ManagementVNICSpec) GetMinBandwidthWeight() int32 {
	if x != nil {
		return x.MinBandwidthWeight
	}
	return 0
}

type IPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DnsServers    []string               `protobuf:"bytes,3,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPConfig) Reset() {
	*x = IPConfig{}
	mi := &file_ballast_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPConfig) ProtoMessage() {}

func (x *IPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPConfig.ProtoReflect.Descriptor instead.
func (*IPConfig) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{17}
}

func (x *IPConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IPConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *IPConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

type HostStorageSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContributeToS2D      bool                   `protobuf:"varint,1,opt,name=contribute_to_s2d,json=contributeToS2d,proto3" json:"contribute_to_s2d,omitempty"`
	EligibleDiskSelector map[string]string      `protobuf:"bytes,2,rep,name=eligible_disk_selector,json=eligibleDiskSelector,proto3" json:"eligible_disk_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HostStorageSpec) Reset() {
	*x = HostStorageSpec{}
	mi := &file_ballast_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStorageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStorageSpec) ProtoMessage() {}

func (x *HostStorageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStorageSpec.ProtoReflect.Descriptor instead.
func (*HostStorageSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{18}
}

func (x *HostStorageSpec) GetContributeToS2D() bool {
	if x != nil {
		return x.ContributeToS2D
	}
	return false
}

func (x *HostStorageSpec) GetEligibleDiskSelector() map[string]string {
	if x != nil {
		return x.EligibleDiskSelector
	}
	return nil
}

type ClusterMembershipSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMembershipSpec) Reset() {
	*x = ClusterMembershipSpec{}
	mi := &file_ballast_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMembershipSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMembershipSpec) ProtoMessage() {}

func (x *ClusterMembershipSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMembershipSpec.ProtoReflect.Descriptor instead.
func (*ClusterMembershipSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{19}
}

func (x *ClusterMembershipSpec) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// ClusterAssignment is delivered to an agent that belongs to a cluster. It
// names whether this host is the designated former (the single member that runs
// Test-Cluster/New-Cluster) and carries the cluster's desired state so the
// former can act on it. Non-formers use it to know their cluster and report.
type ClusterAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	IsFormer      bool                   `protobuf:"varint,2,opt,name=is_former,json=isFormer,proto3" json:"is_former,omitempty"`
	Cluster       *Cluster               `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterAssignment) Reset() {
	*x = ClusterAssignment{}
	mi := &file_ballast_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterAssignment) ProtoMessage() {}

func (x *ClusterAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterAssignment.ProtoReflect.Descriptor instead.
func (*ClusterAssignment) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{20}
}

func (x *ClusterAssignment) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *ClusterAssignment) GetIsFormer() bool {
	if x != nil {
		return x.IsFormer
	}
	return false
}

func (x *ClusterAssignment) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec          *ClusterSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ClusterStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_ballast_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{21}
}

func (x *Cluster) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Cluster) GetSpec() *ClusterSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Cluster) GetStatus() *ClusterStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ClusterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// members are the host names that should form the cluster.
	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// management_ip is the cluster's virtual management address (CIDR or plain).
	ManagementIp string       `protobuf:"bytes,2,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	Witness      *WitnessSpec `protobuf:"bytes,3,opt,name=witness,proto3" json:"witness,omitempty"`
	// enable_s2d requests Storage Spaces Direct once the cluster is formed.
	EnableS2D     bool `protobuf:"varint,4,opt,name=enable_s2d,json=enableS2d,proto3" json:"enable_s2d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSpec) Reset() {
	*x = ClusterSpec{}
	mi := &file_ballast_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSpec) ProtoMessage() {}

func (x *ClusterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSpec.ProtoReflect.Descriptor instead.
func (*ClusterSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{22}
}

func (x *ClusterSpec) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ClusterSpec) GetManagementIp() string {
	if x != nil {
		return x.ManagementIp
	}
	return ""
}

func (x *ClusterSpec) GetWitness() *WitnessSpec {
	if x != nil {
		return x.Witness
	}
	return nil
}

func (x *ClusterSpec) GetEnableS2D() bool {
	if x != nil {
		return x.EnableS2D
	}
	return false
}

type WitnessSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WitnessType            `protobuf:"varint,1,opt,name=type,proto3,enum=ballast.v1.WitnessType" json:"type,omitempty"`
	FileSharePath string                 `protobuf:"bytes,2,opt,name=file_share_path,json=fileSharePath,proto3" json:"file_share_path,omitempty"`
	CloudAccount  string                 `protobuf:"bytes,3,opt,name=cloud_account,json=cloudAccount,proto3" json:"cloud_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessSpec) Reset() {
	*x = WitnessSpec{}
	mi := &file_ballast_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessSpec) ProtoMessage() {}

func (x *WitnessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessSpec.ProtoReflect.Descriptor instead.
func (*WitnessSpec) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{23}
}

func (x *WitnessSpec) GetType() WitnessType {
	if x != nil {
		return x.Type
	}
	return WitnessType_WITNESS_TYPE_UNSPECIFIED
}

func (x *WitnessSpec) GetFileSharePath() string {
	if x != nil {
		return x.FileSharePath
	}
	return ""
}

func (x *WitnessSpec) GetCloudAccount() string {
	if x != nil {
		return x.CloudAccount
	}
	return ""
}

type ClusterStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Phase              Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=ballast.v1.Phase" json:"phase,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,2,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	FormedMembers      []string               `protobuf:"bytes,3,rep,name=formed_members,json=formedMembers,proto3" json:"formed_members,omitempty"`
	S2DEnabled         bool                   `protobuf:"varint,4,opt,name=s2d_enabled,json=s2dEnabled,proto3" json:"s2d_enabled,omitempty"`
	Conditions         []*Condition           `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_ballast_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ballast_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_ballast_proto_rawDescGZIP(), []int{24}
}

func (x *ClusterStatus) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *ClusterStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *ClusterStatus) GetFormedMembers() []string {
	if x != nil {
		return x.FormedMembers
	}
	return nil
}

func (x *ClusterStatus) GetS2DEnabled() bool {
	if x != nil {
		return x.S2DEnabled
	}
	return false
}

func (x *ClusterStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_ballast_proto protoreflect.FileDescriptor

const file_ballast_proto_rawDesc = "" +
	"\n" +
	"\rballast.proto\x12\n" +
	"ballast.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\x13RegisterHostRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x127\n" +
	"\tinventory\x18\x03 \x01(\v2\x19.ballast.v1.HostInventoryR\tinventory\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\">\n" +
	"\x14RegisterHostResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05known\x18\x02 \x01(\bR\x05known\"s\n" +
	"\x17PullDesiredStateRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12)\n" +
	"\x10known_generation\x18\x03 \x01(\x03R\x0fknownGeneration\"\xd8\x01\n" +
	"\x18PullDesiredStateResponse\x12*\n" +
	"\x11has_desired_state\x18\x01 \x01(\bR\x0fhasDesiredState\x12\x1c\n" +
	"\tunchanged\x18\x02 \x01(\bR\tunchanged\x12$\n" +
	"\x04host\x18\x03 \x01(\v2\x10.ballast.v1.HostR\x04host\x12L\n" +
	"\x12cluster_assignment\x18\x04 \x01(\v2\x1d.ballast.v1.ClusterAssignmentR\x11clusterAssignment\"\xd9\x01\n" +
	"\x13ReportStatusRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12.\n" +
	"\x06status\x18\x03 \x01(\v2\x16.ballast.v1.HostStatusR\x06status\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12@\n" +
	"\x0ecluster_status\x18\x05 \x01(\v2\x19.ballast.v1.ClusterStatusR\rclusterStatus\"2\n" +
	"\x14ReportStatusResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xbf\x02\n" +
	"\n" +
	"ObjectMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12:\n" +
	"\x06labels\x18\x04 \x03(\v2\".ballast.v1.ObjectMeta.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12L\n" +
	"\x14last_transition_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\"\x8c\x01\n" +
	"\x04Host\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.ballast.v1.ObjectMetaR\x04meta\x12(\n" +
	"\x04spec\x18\x02 \x01(\v2\x14.ballast.v1.HostSpecR\x04spec\x12.\n" +
	"\x06status\x18\x03 \x01(\v2\x16.ballast.v1.HostStatusR\x06status\"\xd4\x02\n" +
	"\bHostSpec\x12\x12\n" +
	"\x04fqdn\x18\x01 \x01(\tR\x04fqdn\x12,\n" +
	"\x12enable_hyperv_role\x18\x02 \x01(\bR\x10enableHypervRole\x12>\n" +
	"\n" +
	"networking\x18\x03 \x01(\v2\x1e.ballast.v1.HostNetworkingSpecR\n" +
	"networking\x125\n" +
	"\astorage\x18\x04 \x01(\v2\x1b.ballast.v1.HostStorageSpecR\astorage\x12P\n" +
	"\x12cluster_membership\x18\x05 \x01(\v2!.ballast.v1.ClusterMembershipSpecR\x11clusterMembership\x12=\n" +
	"\rreboot_policy\x18\x06 \x01(\x0e2\x18.ballast.v1.RebootPolicyR\frebootPolicy\"\x89\x03\n" +
	"\n" +
	"HostStatus\x12'\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x11.ballast.v1.PhaseR\x05phase\x12/\n" +
	"\x13observed_generation\x18\x02 \x01(\x03R\x12observedGeneration\x12)\n" +
	"\x10hyperv_installed\x18\x03 \x01(\bR\x0fhypervInstalled\x12'\n" +
	"\x0freboot_required\x18\x04 \x01(\bR\x0erebootRequired\x12\x1e\n" +
	"\n" +
	"autonomous\x18\x05 \x01(\bR\n" +
	"autonomous\x12=\n" +
	"\flast_contact\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastContact\x127\n" +
	"\tinventory\x18\a \x01(\v2\x19.ballast.v1.HostInventoryR\tinventory\x125\n" +
	"\n" +
	"conditions\x18\b \x03(\v2\x15.ballast.v1.ConditionR\n" +
	"conditions\"\xeb\x01\n" +
	"\rHostInventory\x12H\n" +
	"\x11physical_adapters\x18\x01 \x03(\v2\x1b.ballast.v1.PhysicalAdapterR\x10physicalAdapters\x12?\n" +
	"\x0ephysical_disks\x18\x02 \x03(\v2\x18.ballast.v1.PhysicalDiskR\rphysicalDisks\x12,\n" +
	"\x12total_memory_bytes\x18\x03 \x01(\x04R\x10totalMemoryBytes\x12!\n" +
	"\flogical_cpus\x18\x04 \x01(\x05R\vlogicalCpus\"m\n" +
	"\x0fPhysicalAdapter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12$\n" +
	"\x0elink_speed_bps\x18\x03 \x01(\x04R\flinkSpeedBps\x12\x0e\n" +
	"\x02up\x18\x04 \x01(\bR\x02up\"\x84\x01\n" +
	"\fPhysicalDisk\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x19\n" +
	"\bcan_pool\x18\x04 \x01(\bR\acanPool\"\x9a\x01\n" +
	"\x12HostNetworkingSpec\x129\n" +
	"\bswitches\x18\x01 \x03(\v2\x1d.ballast.v1.VirtualSwitchSpecR\bswitches\x12I\n" +
	"\x10management_vnics\x18\x02 \x03(\v2\x1e.ballast.v1.ManagementVNICSpecR\x0fmanagementVnics\"\xfe\x01\n" +
	"\x11VirtualSwitchSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fteam_members\x18\x02 \x03(\tR\vteamMembers\x12=\n" +
	"\fteaming_mode\x18\x03 \x01(\x0e2\x1a.ballast.v1.SETTeamingModeR\vteamingMode\x12C\n" +
	"\x0eload_balancing\x18\x04 \x01(\x0e2\x1c.ballast.v1.SETLoadBalancingR\rloadBalancing\x12.\n" +
	"\x13allow_management_os\x18\x05 \x01(\bR\x11allowManagementOs\"\xc7\x01\n" +
	"\x12ManagementVNICSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vswitch_name\x18\x02 \x01(\tR\n" +
	"switchName\x12\x17\n" +
	"\avlan_id\x18\x03 \x01(\x05R\x06vlanId\x121\n" +
	"\tip_config\x18\x04 \x01(\v2\x14.ballast.v1.IPConfigR\bipConfig\x120\n" +
	"\x14min_bandwidth_weight\x18\x05 \x01(\x05R\x12minBandwidthWeight\"_\n" +
	"\bIPConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x1f\n" +
	"\vdns_servers\x18\x03 \x03(\tR\n" +
	"dnsServers\"\xf3\x01\n" +
	"\x0fHostStorageSpec\x12*\n" +
	"\x11contribute_to_s2d\x18\x01 \x01(\bR\x0fcontributeToS2d\x12k\n" +
	"\x16eligible_disk_selector\x18\x02 \x03(\v25.ballast.v1.HostStorageSpec.EligibleDiskSelectorEntryR\x14eligibleDiskSelector\x1aG\n" +
	"\x19EligibleDiskSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x15ClusterMembershipSpec\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"|\n" +
	"\x11ClusterAssignment\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x1b\n" +
	"\tis_former\x18\x02 \x01(\bR\bisFormer\x12-\n" +
	"\acluster\x18\x03 \x01(\v2\x13.ballast.v1.ClusterR\acluster\"\x95\x01\n" +
	"\aCluster\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.ballast.v1.ObjectMetaR\x04meta\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.ballast.v1.ClusterSpecR\x04spec\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.ballast.v1.ClusterStatusR\x06status\"\x9e\x01\n" +
	"\vClusterSpec\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\x12#\n" +
	"\rmanagement_ip\x18\x02 \x01(\tR\fmanagementIp\x121\n" +
	"\awitness\x18\x03 \x01(\v2\x17.ballast.v1.WitnessSpecR\awitness\x12\x1d\n" +
	"\n" +
	"enable_s2d\x18\x04 \x01(\bR\tenableS2d\"\x87\x01\n" +
	"\vWitnessSpec\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.ballast.v1.WitnessTypeR\x04type\x12&\n" +
	"\x0ffile_share_path\x18\x02 \x01(\tR\rfileSharePath\x12#\n" +
	"\rcloud_account\x18\x03 \x01(\tR\fcloudAccount\"\xe8\x01\n" +
	"\rClusterStatus\x12'\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x11.ballast.v1.PhaseR\x05phase\x12/\n" +
	"\x13observed_generation\x18\x02 \x01(\x03R\x12observedGeneration\x12%\n" +
	"\x0eformed_members\x18\x03 \x03(\tR\rformedMembers\x12\x1f\n" +
	"\vs2d_enabled\x18\x04 \x01(\bR\n" +
	"s2dEnabled\x125\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x15.ballast.v1.ConditionR\n" +
	"conditions*~\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_PENDING\x10\x01\x12\x15\n" +
	"\x11PHASE_PROGRESSING\x10\x02\x12\x0f\n" +
	"\vPHASE_READY\x10\x03\x12\x12\n" +
	"\x0ePHASE_DEGRADED\x10\x04\x12\x0f\n" +
	"\vPHASE_ERROR\x10\x05*c\n" +
	"\fRebootPolicy\x12\x1d\n" +
	"\x19REBOOT_POLICY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REBOOT_POLICY_NEVER\x10\x01\x12\x1b\n" +
	"\x17REBOOT_POLICY_IF_NEEDED\x10\x02*[\n" +
	"\x0eSETTeamingMode\x12 \n" +
	"\x1cSET_TEAMING_MODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#SET_TEAMING_MODE_SWITCH_INDEPENDENT\x10\x01*z\n" +
	"\x10SETLoadBalancing\x12\"\n" +
	"\x1eSET_LOAD_BALANCING_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSET_LOAD_BALANCING_HYPERV_PORT\x10\x01\x12\x1e\n" +
	"\x1aSET_LOAD_BALANCING_DYNAMIC\x10\x02*\x8e\x01\n" +
	"\vWitnessType\x12\x1c\n" +
	"\x18WITNESS_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WITNESS_TYPE_NONE\x10\x01\x12\x1b\n" +
	"\x17WITNESS_TYPE_FILE_SHARE\x10\x02\x12\x16\n" +
	"\x12WITNESS_TYPE_CLOUD\x10\x03\x12\x15\n" +
	"\x11WITNESS_TYPE_DISK\x10\x042\x93\x02\n" +
	"\fAgentService\x12Q\n" +
	"\fRegisterHost\x12\x1f.ballast.v1.RegisterHostRequest\x1a .ballast.v1.RegisterHostResponse\x12]\n" +
	"\x10PullDesiredState\x12#.ballast.v1.PullDesiredStateRequest\x1a$.ballast.v1.PullDesiredStateResponse\x12Q\n" +
	"\fReportStatus\x12\x1f.ballast.v1.ReportStatusRequest\x1a .ballast.v1.ReportStatusResponseB6Z4github.com/joshua-fourie/ballast/api/proto;ballastpbb\x06proto3"

var (
	file_ballast_proto_rawDescOnce sync.Once
	file_ballast_proto_rawDescData []byte
)

func file_ballast_proto_rawDescGZIP() []byte {
	file_ballast_proto_rawDescOnce.Do(func() {
		file_ballast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ballast_proto_rawDesc), len(file_ballast_proto_rawDesc)))
	})
	return file_ballast_proto_rawDescData
}

var file_ballast_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ballast_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_ballast_proto_goTypes = []any{
	(Phase)(0),                       // 0: ballast.v1.Phase
	(RebootPolicy)(0),                // 1: ballast.v1.RebootPolicy
	(SETTeamingMode)(0),              // 2: ballast.v1.SETTeamingMode
	(SETLoadBalancing)(0),            // 3: ballast.v1.SETLoadBalancing
	(WitnessType)(0),                 // 4: ballast.v1.WitnessType
	(*RegisterHostRequest)(nil),      // 5: ballast.v1.RegisterHostRequest
	(*RegisterHostResponse)(nil),     // 6: ballast.v1.RegisterHostResponse
	(*PullDesiredStateRequest)(nil),  // 7: ballast.v1.PullDesiredStateRequest
	(*PullDesiredStateResponse)(nil), // 8: ballast.v1.PullDesiredStateResponse
	(*ReportStatusRequest)(nil),      // 9: ballast.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil),     // 10: ballast.v1.ReportStatusResponse
	(*ObjectMeta)(nil),               // 11: ballast.v1.ObjectMeta
	(*Condition)(nil),                // 12: ballast.v1.Condition
	(*Host)(nil),                     // 13: ballast.v1.Host
	(*HostSpec)(nil),                 // 14: ballast.v1.HostSpec
	(*HostStatus)(nil),               // 15: ballast.v1.HostStatus
	(*HostInventory)(nil),            // 16: ballast.v1.HostInventory
	(*PhysicalAdapter)(nil),          // 17: ballast.v1.PhysicalAdapter
	(*PhysicalDisk)(nil),             // 18: ballast.v1.PhysicalDisk
	(*HostNetworkingSpec)(nil),       // 19: ballast.v1.HostNetworkingSpec
	(*VirtualSwitchSpec)(nil),        // 20: ballast.v1.VirtualSwitchSpec
	(*ManagementVNICSpec)(nil),       // 21: ballast.v1.ManagementVNICSpec
	(*IPConfig)(nil),                 // 22: ballast.v1.IPConfig
	(*HostStorageSpec)(nil),          // 23: ballast.v1.HostStorageSpec
	(*ClusterMembershipSpec)(nil),    // 24: ballast.v1.ClusterMembershipSpec
	(*ClusterAssignment)(nil),        // 25: ballast.v1.ClusterAssignment
	(*Cluster)(nil),                  // 26: ballast.v1.Cluster
	(*ClusterSpec)(nil),              // 27: ballast.v1.ClusterSpec
	(*WitnessSpec)(nil),              // 28: ballast.v1.WitnessSpec
	(*ClusterStatus)(nil),            // 29: ballast.v1.ClusterStatus
	nil,                              // 30: ballast.v1.ObjectMeta.LabelsEntry
	nil,                              // 31: ballast.v1.HostStorageSpec.EligibleDiskSelectorEntry
	(*timestamppb.Timestamp)(nil),    // 32: google.protobuf.Timestamp
}
var file_ballast_proto_depIdxs = []int32{
	16, // 0: ballast.v1.RegisterHostRequest.inventory:type_name -> ballast.v1.HostInventory
	13, // 1: ballast.v1.PullDesiredStateResponse.host:type_name -> ballast.v1.Host
	25, // 2: ballast.v1.PullDesiredStateResponse.cluster_assignment:type_name -> ballast.v1.ClusterAssignment
	15, // 3: ballast.v1.ReportStatusRequest.status:type_name -> ballast.v1.HostStatus
	29, // 4: ballast.v1.ReportStatusRequest.cluster_status:type_name -> ballast.v1.ClusterStatus
	30, // 5: ballast.v1.ObjectMeta.labels:type_name -> ballast.v1.ObjectMeta.LabelsEntry
	32, // 6: ballast.v1.ObjectMeta.created_at:type_name -> google.protobuf.Timestamp
	32, // 7: ballast.v1.ObjectMeta.updated_at:type_name -> google.protobuf.Timestamp
	32, // 8: ballast.v1.Condition.last_transition_time:type_name -> google.protobuf.Timestamp
	11, // 9: ballast.v1.Host.meta:type_name -> ballast.v1.ObjectMeta
	14, // 10: ballast.v1.Host.spec:type_name -> ballast.v1.HostSpec
	15, // 11: ballast.v1.Host.status:type_name -> ballast.v1.HostStatus
	19, // 12: ballast.v1.HostSpec.networking:type_name -> ballast.v1.HostNetworkingSpec
	23, // 13: ballast.v1.HostSpec.storage:type_name -> ballast.v1.HostStorageSpec
	24, // 14: ballast.v1.HostSpec.cluster_membership:type_name -> ballast.v1.ClusterMembershipSpec
	1,  // 15: ballast.v1.HostSpec.reboot_policy:type_name -> ballast.v1.RebootPolicy
	0,  // 16: ballast.v1.HostStatus.phase:type_name -> ballast.v1.Phase
	32, // 17: ballast.v1.HostStatus.last_contact:type_name -> google.protobuf.Timestamp
	16, // 18: ballast.v1.HostStatus.inventory:type_name -> ballast.v1.HostInventory
	12, // 19: ballast.v1.HostStatus.conditions:type_name -> ballast.v1.Condition
	17, // 20: ballast.v1.HostInventory.physical_adapters:type_name -> ballast.v1.PhysicalAdapter
	18, // 21: ballast.v1.HostInventory.physical_disks:type_name -> ballast.v1.PhysicalDisk
	20, // 22: ballast.v1.HostNetworkingSpec.switches:type_name -> ballast.v1.VirtualSwitchSpec
	21, // 23: ballast.v1.HostNetworkingSpec.management_vnics:type_name -> ballast.v1.ManagementVNICSpec
	2,  // 24: ballast.v1.VirtualSwitchSpec.teaming_mode:type_name -> ballast.v1.SETTeamingMode
	3,  // 25: ballast.v1.VirtualSwitchSpec.load_balancing:type_name -> ballast.v1.SETLoadBalancing
	22, // 26: ballast.v1.ManagementVNICSpec.ip_config:type_name -> ballast.v1.IPConfig
	31, // 27: ballast.v1.HostStorageSpec.eligible_disk_selector:type_name -> ballast.v1.HostStorageSpec.EligibleDiskSelectorEntry
	26, // 28: ballast.v1.ClusterAssignment.cluster:type_name -> ballast.v1.Cluster
	11, // 29: ballast.v1.Cluster.meta:type_name -> ballast.v1.ObjectMeta
	27, // 30: ballast.v1.Cluster.spec:type_name -> ballast.v1.ClusterSpec
	29, // 31: ballast.v1.Cluster.status:type_name -> ballast.v1.ClusterStatus
	28, // 32: ballast.v1.ClusterSpec.witness:type_name -> ballast.v1.WitnessSpec
	4,  // 33: ballast.v1.WitnessSpec.type:type_name -> ballast.v1.WitnessType
	0,  // 34: ballast.v1.ClusterStatus.phase:type_name -> ballast.v1.Phase
	12, // 35: ballast.v1.ClusterStatus.conditions:type_name -> ballast.v1.Condition
	5,  // 36: ballast.v1.AgentService.RegisterHost:input_type -> ballast.v1.RegisterHostRequest
	7,  // 37: ballast.v1.AgentService.PullDesiredState:input_type -> ballast.v1.PullDesiredStateRequest
	9,  // 38: ballast.v1.AgentService.ReportStatus:input_type -> ballast.v1.ReportStatusRequest
	6,  // 39: ballast.v1.AgentService.RegisterHost:output_type -> ballast.v1.RegisterHostResponse
	8,  // 40: ballast.v1.AgentService.PullDesiredState:output_type -> ballast.v1.PullDesiredStateResponse
	10, // 41: ballast.v1.AgentService.ReportStatus:output_type -> ballast.v1.ReportStatusResponse
	39, // [39:42] is the sub-list for method output_type
	36, // [36:39] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_ballast_proto_init() }
func file_ballast_proto_init() {
	if File_ballast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ballast_proto_rawDesc), len(file_ballast_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ballast_proto_goTypes,
		DependencyIndexes: file_ballast_proto_depIdxs,
		EnumInfos:         file_ballast_proto_enumTypes,
		MessageInfos:      file_ballast_proto_msgTypes,
	}.Build()
	File_ballast_proto = out.File
	file_ballast_proto_goTypes = nil
	file_ballast_proto_depIdxs = nil
}
